version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: >-
    set PATH=C:\Python37;C:\Python37\\Scripts;%PATH%

    python -m pip install --upgrade pip

    pip install wheel

    pip install robotframework

    pip install robotframework-whitelibrary
build: off
test_script:
- ps: robot -x xunit-result.xml -d result --nostatusrc Automation.robot
artifacts:
- path: result/
  name: results
on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\result\xunit-result.xml))