version: 1.0.{build}
image: Visual Studio 2022
environment:
  matrix:
    - job_name: Python 3.8 x86
      PYTHON: "C:\\Python38"
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 32

    - job_name: Python 3.9 x86
      PYTHON: "C:\\Python39"
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 32

    - job_name: Python 3.10 x86
      PYTHON: "C:\\Python310"
      PYTHON_VERSION: 3.10
      PYTHON_ARCH: 32

    - job_name: Python 3.8 x64
      PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 64

    - job_name: Python 3.9 x64
      PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 64

    - job_name: Python 3.10 x64
      PYTHON: "C:\\Python310-x64"
      PYTHON_VERSION: 3.10
      PYTHON_ARCH: 64
init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
install:
- cmd: >-
    set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    
    python --version

    python -m pip install --upgrade pip
    
    .\keen.bat dependency
build: off
test_script:
- cmd: .\keen.bat test
artifacts:
- path: result/
  name: results
on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\result\xunit-result.xml))