version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: >-
    set PATH=C:\Python37;C:\Python37\\Scripts;%PATH%
    
    .\test_execution.bat install
build: off
test_script:
- cmd: >-
    .\test_execution.bat testing
artifacts:
- path: result/
  name: results
on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\result\xunit.xml))